AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy StarRocks on Amazon Web Services in an existing VPC. ()
Metadata:
  QuickStartDocumentation:
    EntrypointName: Launch into an existing VPC
    Order: "5"
  QSLint:
    Exclusions: [ W9002, W9003, W9004, W9006 ]
  cfn-lint:
    config:
      ignore_checks:
        - E9101
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - NumberOfAZs
          - VPCID
          - VPCCIDR
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PrivateSubnet3ID
          - PublicSubnet1ID
          - PublicSubnet2ID
          - PublicSubnet3ID
          - RemoteAccessCIDR
    - Label:
        default: Quick Start configuration
      Parameters:
        - QSS3BucketName
        - QSS3KeyPrefix
        - QSS3BucketRegion
        - RemoteAccessCIDR
    - Label:
        default: EC2 configuration
      Parameters:
        - KeyPairName
    - Label:
        default: Environment configuration
      Parameters:
        - LatestAmiId
        - JDKDownLoadURL
        - StarRocksDownLoadURL

    # StarRocks Cluster configuration
    - Label:
        default: StarRocks Cluster configuration
      Parameters:
        - FeNodeCount
        - FeNodeInstanceType
        - BeNodeCount
        - BeNodeInstanceType

    # Fe configuration
    - Label:
        default: Fe configuration
      Parameters:
        - LogDir
        - LogLevel
        - MetaDir

    # BE configuration
    - Label:
        default: BE configuration
      Parameters:
        - SysLogDir
        - SysLogLevel
        - VolumeType
        - VolumeSize
    ParameterLabels:
      NumberOfAZs:
        default: Number of Availability Zones
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PublicSubnet3ID:
        default: Public subnet 3 ID
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      RemoteAccessCIDR:
        default: Allowed bastion external access CIDR
      VPCID:
        default: VPC ID
      VPCCIDR:
        default: VPC CIDR
      KeyPairName:
        default: Key pair name
      LatestAmiId:
        default: Reference the latest Amazon Linux AMI in a CloudFormation template
      JDKDownLoadURL:
        default: URL of download JDK 1.8
      StarRocksDownLoadURL:
        default: URL of StarRocks
      FeNodeCount:
        default: Number of StarRocks Fe
      FeNodeInstanceType:
        default: Fe instance type
      BeNodeCount:
        default: Number of StarRocks Be
      BeNodeInstanceType:
        default: Be instance type

      # FE
      LogLevel:
        default: Sys Log Level
      MetaDir:
        default: Meta data dir
      LogDir:
        default: log dir

      # BE
      SysLogLevel:
        default: Sys Log Level
      VolumeType:
        default: Volume type of Be nodes
      VolumeSize:
        default: Volume size of Be nodes
      SysLogDir:
        default: Default SysLog Dir
Parameters:
  PublicSubnet1ID:
    Type: String
    Description: ID of the public subnet in Availability Zone 1 of your existing VPC (e.g., subnet-a0246dcd).
    Default: ""
  PublicSubnet2ID:
    Type: String
    Description: ID of the public subnet in Availability Zone 2 of your existing VPC (e.g., subnet-b1236eea).
    Default: ""
  PublicSubnet3ID:
    Type: String
    Description: ID of the public subnet in Availability Zone 3 of your existing VPC (e.g., subnet-c3456aba).
    Default: ""
  PrivateSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: ID of the private subnet in Availability Zone 1 of your existing VPC (e.g., subnet-fe9a8b32).
  PrivateSubnet2ID:
    Type: String
    Description: ID of the private subnet in Availability Zone 2 of your existing VPC (e.g., subnet-be8b01ea).
    Default: ""
  PrivateSubnet3ID:
    Type: String
    Description: ID of the private subnet in Availability Zone 3 of your existing VPC (e.g., subnet-abd39039).
    Default: ""
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a
      hyphen (-).
    Default: aws-quickstart
    Description:
      Name of the S3 bucket for your copy of the Quick Start assets.
      Keep the default name unless you are customizing the template.
      Changing the name updates code references to point to a new Quick
      Start location. This name can include numbers, lowercase letters,
      uppercase letters, and hyphens, but do not start or end with a hyphen (-).
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Public/private key pairs to connect to your instance after deployment.
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access to the bastions
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: ID of your existing VPC (e.g., vpc-0343606e).
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16–28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    Type: String
    ConstraintDescription:
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/). The prefix should
      end with a forward slash (/).
    Default: quickstart-starrocks-starrocks/
    Description:
      S3 key prefix that is used to simulate a directory for your copy of the
      Quick Start assets. Keep the default prefix unless you are customizing
      the template. Changing this prefix updates code references to point to
      a new Quick Start location. This prefix can include numbers, lowercase
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with
      a forward slash. See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
      and https://aws-quickstart.github.io/option1.html.
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is
      hosted. Keep the default Region unless you are customizing the template.
      Changing this Region updates code references to point to a new Quick Start location.
      When using your own bucket, specify the Region.
      See https://aws-quickstart.github.io/option1.html.'
    Type: String
  NumberOfAZs:
    Type: String
    AllowedValues: [ "2"]
    Default: "2"
    Description: Number of Availability Zones to use in the VPC. This must match the value entered for the AvailabilityZones parameter.
  LatestAmiId:
    Description: Reference the latest Amazon Linux AMI in a CloudFormation template.
    Type: AWS::EC2::Image::Id
#Default: ami-0d648a61f4ab8d0e2
    Default: ami-0cff7528ff583bf9a
  JDKDownLoadURL:
    Description: URL of download JDK 1.8
    Type: String
    Default: https://cdn-thirdparty.starrocks.com/java-se-8u41-ri.tar.gz
  StarRocksDownLoadURL:
    Description: URL of StarRocks
    Type: String
#Default: https://www.starrocks.com/zh-CN/download/request-download/12
    Default: https://download.starrocks.com/en-us/download/request-download/31/
  FeNodeCount:
    Type: Number
    Default: 1
    Description: Number of StarRocks Fe
    AllowedValues:
      - 1
      - 3
  FeNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for fe instances.
    Type: String
  BeNodeCount:
    Type: Number
    Default: 3
    Description: Number of StarRocks Be
    AllowedValues:
      - 3
      - 4
      - 5
      - 6
  BeNodeInstanceType:
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
    Default: t2.micro
    Description: Amazon EC2 instance type for be instances.
    Type: String

  # Fe
  LogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues:
      - INFO
      - WARN
      - ERROR
      - FATAL
  MetaDir:
    Description: Dir to save mete data, please to fill in the absolute path
    Type: String
    Default: feDefaultMetaPath

  # Be
  SysLogLevel:
    Description: Sys Log Level, please select from the drop-down menu
    Type: String
    Default: INFO
    AllowedValues:
      - INFO
      - WARN
      - ERROR
      - FATAL
  VolumeType:
    Type: String
    Description: EBS volume type (data) to be attached to node in GBs [gp2,gp3,st1], one volume for data storage is mounted automatically by CloudFormation stack.
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - st1
      - io1
  VolumeSize:
    Type: String
    Description: EBS volume size (data) to be attached to node in GBs.
    Default: 50
  LogDir:
    Type: String
    Description: Default Path for Log Files.
    Default: feDefaultLogPath
  SysLogDir:
    Type: String
    Description: Default Path for SysLog Files.
    Default: beDefaultLogPath
Conditions:
  4BeNodesCondition: !Or
    - !Equals [ !Ref 'BeNodeCount', '4' ]
    - !Equals [ !Ref 'BeNodeCount', '5' ]
    - !Equals [ !Ref 'BeNodeCount', '6' ]
  5BeNodesCondition: !Or
    - !Equals [ !Ref 'BeNodeCount', '5' ]
    - !Equals [ !Ref 'BeNodeCount', '6' ]
  6BeNodesCondition: !Equals [ !Ref 'BeNodeCount', '6' ]
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        VPCID: !Ref VPCID
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        KeyPairName: !Ref KeyPairName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Sub '${QSS3KeyPrefix}submodules/quickstart-linux-bastion/'
        QSS3BucketRegion: !Ref QSS3BucketRegion
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/starrocks_securitygroups.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        VPCID: !Ref VPCID
        VPCCIDR: !Ref VPCCIDR
        BastionSecurityGroupID: !GetAtt BastionStack.Outputs.BastionSecurityGroupID
  BeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/starrocks_be.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        BeNodeCount: !Ref BeNodeCount
        PrivateSubnetID: !Ref PrivateSubnet1ID
        StarRocksServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.StarRocksServerSecurityGroup
        KeyPairName: !Ref KeyPairName
        LatestAmiId: !Ref LatestAmiId
        JDKDownLoadURL: !Ref JDKDownLoadURL
        StarRocksDownLoadURL: !Ref StarRocksDownLoadURL
        BeNodeInstanceType: !Ref BeNodeInstanceType
        SysLogDir: !Ref SysLogDir
        SysLogLevel: !Ref SysLogLevel
        VolumeType: !Ref VolumeType
        VolumeSize: !Ref VolumeSize
  FeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/starrocks_fe.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        PrivateSubnetID: !Ref PrivateSubnet1ID
        StarRocksServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.StarRocksServerSecurityGroup
        KeyPairName: !Ref KeyPairName
        LatestAmiId: !Ref LatestAmiId
        JDKDownLoadURL: !Ref JDKDownLoadURL
        StarRocksDownLoadURL: !Ref StarRocksDownLoadURL
        FeNodeInstanceType: !Ref FeNodeInstanceType
        FeNodeCount: !Ref FeNodeCount
        LogDir: !Ref LogDir
        SysLogLevel: !Ref LogLevel
        MetaDir: !Ref MetaDir
        VolumeType: !Ref VolumeType
        BeInstancePrivateIp1: !GetAtt BeStack.Outputs.BeInstancePrivateIp1
        BeInstancePrivateIp2: !GetAtt BeStack.Outputs.BeInstancePrivateIp2
        BeInstancePrivateIp3: !GetAtt BeStack.Outputs.BeInstancePrivateIp3
        BeInstancePrivateIp4: !If
          - 4BeNodesCondition
          - !GetAtt BeStack.Outputs.BeInstancePrivateIp4
          - 0.0.0.0
        BeInstancePrivateIp5: !If
          - 5BeNodesCondition
          - !GetAtt BeStack.Outputs.BeInstancePrivateIp5
          - 0.0.0.0
        BeInstancePrivateIp6: !If
          - 6BeNodesCondition
          - !GetAtt BeStack.Outputs.BeInstancePrivateIp6
          - 0.0.0.0
